services:
  db:
    image: bitnami/postgresql:latest
    container_name: brevly-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=brevly
    volumes:
      - "./docker:/docker-entrypoint-initdb.d"
    networks:
      - server
      - db


  server:
    build: .
    depends_on:
      - db
    restart: unless-stopped
    container_name: brevly-server
    ports:
      - $PORT:$PORT
    environment:
      - $PORT:$PORT
      - DATABASE_URL=$DATABASE_URL
      - CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID
      - CLOUDFLARE_ACCESS_KEY_ID=$CLOUDFLARE_ACCESS_KEY_ID
      - CLOUDFLARE_SECRET_ACCESS_KEY=$CLOUDFLARE_SECRET_ACCESS_KEY
      - CLOUDFLARE_BUCKET=$CLOUDFLARE_BUCKET
      - CLOUDFLARE_PUBLIC_URL=$CLOUDFLARE_PUBLIC_URL
    networks:
      - server

volumes:
  db:

networks:
  server:
    driver: bridge
  db:
    driver: bridge

