/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShortLinkRouteImport } from './routes/$short-link'
import { Route as IndexRouteImport } from './routes/index'

const ShortLinkRoute = ShortLinkRouteImport.update({
  id: '/$short-link',
  path: '/$short-link',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$short-link': typeof ShortLinkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$short-link': typeof ShortLinkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$short-link': typeof ShortLinkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$short-link'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$short-link'
  id: '__root__' | '/' | '/$short-link'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShortLinkRoute: typeof ShortLinkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$short-link': {
      id: '/$short-link'
      path: '/$short-link'
      fullPath: '/$short-link'
      preLoaderRoute: typeof ShortLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShortLinkRoute: ShortLinkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
